bot:
    token: 'MTI5NzU3NTYzNzU3MzE3MzMwMA.GV0f4Z.5RkStRnKZPcmxZ8N4OIOBbgugoqtBurhjX5bys'
    developer_user_ids:
        - 1129342265723211827
    developer_guild_ids:
        - 1180507199664033852
    developer_channel_ids:
        - 1180507201283039292
    prefix: '!'
    verification_role_id: "1298033227457499259"

db: 'mongodb+srv://ndv_310:ndv_310@cluster0.iyfagot.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0'
